# Generated by Django 3.1.5 on 2021-02-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='string_gauge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
